### PR TITLE
[WIP] Migrating Material-UI

### LINKED ISSUE #2: Update Material-UI
We still have components which are based on material-ui@0.20.2.
New components are already updated to @material-ui/core@3.7.0.

The task is to update all old components without changing the look and feel (small changes are fine) and remove the old dependency.

The old documentation is available on https://v0.material-ui.com/.
The new one: https://material-ui.com/

Most of the components should be easy to update, but it is not a simple search and replace task.
Some properties changed.

We can still use the `style` property for css. Later we will use classes/jss.

### PR DESCRIPTION
**Pull request by DivyeshPuri**
Fixes #2

### CODE REVIEW

**Comment by lmachens** [comment]
@DivyeshPuri Hi, what is the status? You need help?
Maybe it makes sense to split this PR into smaller ones.

**Comment by DivyeshPuri** [comment]
@lmachens I think I am done with updating the material-ui version. Can you please review it :smile:

**Comment by lmachens** [comment]
Please take a look at your changed files https://github.com/lmachens/trophy-hunter/pull/22/files
There are files with existing merge conflicts and some symlinks are removed. And some new `~HEAD` files.

**Comment by DivyeshPuri** [comment]
@lmachens Please take a look if everything is fine.

**Comment by lmachens** [comment]
@DivyeshPuri https://github.com/lmachens/trophy-hunter/pull/22/files doesn't look right. It is impossible to find out what you changed, it removes symlinks and undu changes I did in the meantime.
Only thing I can do is to take a look at your commits to find out what you tried to change.

Thanks again for your time, but I can not merge this without breaking everything.
As an advice, create small pull requests in the future and always check what you commited.

**Pull request closed without merging**
